### ISSUE TITLE
Error: Failed with error: No such Project : peote-layout

### ISSUE THREAD

**Issue by MemeHoovy** [maitag/peote-ui#1]
This happens when trying to install peote-ui, I've already installed it so it's not much of an issue, however it can be for others.

![Screenshot 2022-09-26 193001](https://user-images.githubusercontent.com/97995998/192398473-ec3d3337-373b-4098-a6a6-0f7052f2060a.png)

**Comment by jobf** [comment]
In case anyone comes across this issue it was caused by peote-layout not being available on haxelib but a dependency in the haxelib.json

semmi has fixed the haxelib.json and added extended the readme so hopefully it is a smoother process next time :)

Also worth mentioning is that you would not see the error with `haxelib dev` instead of `haxelib git` - but both should be fine to use!

**Comment by MemeHoovy** [comment]
> In case anyone comes across this issue it was caused by peote-layout not being available on haxelib but a dependency in the haxelib.json
> 
> semmi has fixed the haxelib.json and extended the readme so hopefully it is a smoother process next time :)
> 
> Also worth mentioning is that you would not see the error with `haxelib dev` instead of `haxelib git` - but both should be fine to use!

alrighty then
